### ISSUE TITLE
DSSM有线上测试过效果吗

### ISSUE THREAD

**Issue by skriser** [bbruceyuan/DeepMatch-Torch#2]
如题，想请教下 这些召回模型有实际上线验证码，比如DSSM

**Comment by bbruceyuan** [comment]
你想问的是「这一套代码有没有在线上使用吗」？

**Comment by Wsy002** [comment]
请问MIND在工业里使用的多吗？此外 MIND-torch 的两个塔部分 得到了User Emb 和 Item Emb可以像双塔一样转换成CTR问题嘛

**Comment by bbruceyuan** [comment]
> 请问MIND在工业里使用的多吗？此外 MIND-torch 的两个塔部分 得到了User Emb 和 Item Emb可以像双塔一样转换成CTR问题嘛

mind 在多兴趣召回里面其实用的挺多的。

1. MIND 模型在推荐领域可能用的多一点，因为目标是为了提升用户的体验，所以多样性推荐比较重要。MIND 天然根据用户行为，抽取出不同的兴趣（不同的 embedding），然后和 item 物料计算召回；

2. MIND 训练的目标函数应该就是这个吧。所以答案是可以。
