### ISSUE TITLE
error: ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing'

### ISSUE THREAD

**Issue by HenryBao91** [bbruceyuan/DeepMatch-Torch#6]
我的电脑是 mac book pro
python=3.7
deepctr-torch=0.2.2
tensorflow-macos                  2.8.0

我在 DeepMatch-Torch 的示例里运行了 run_fm_dssm.py 但是没有成功，报错了。
`Traceback (most recent call last):
  File "/Users/henry/PycharmProjects/github/DeepMatch-Torch/examples/run_fm_dssm.py", line 8, in <module>
    from preprocess import gen_data_set, gen_model_input
  File "/Users/henry/PycharmProjects/github/DeepMatch-Torch/examples/preprocess.py", line 4, in <module>
    from tensorflow.python.keras.preprocessing.sequence import pad_sequences
ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing'
WARNING:root:
DeepCTR-PyTorch version 0.2.7 detected. Your version is 0.2.2.
Use `pip install -U deepctr-torch` to upgrade.Changelog: https://github.com/shenweichen/DeepCTR-Torch/releases/tag/v0.2.7`

提示让我安装 deepctr=0.2.7， 但是好像依赖于 TensorFlow ，安装不上
`
(py38) henry@hzMacBookPro DeepMatch-Torch % pip3 install deepctr-torch==0.2.7
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting deepctr-torch==0.2.7
  Using cached http://mirrors.aliyun.com/pypi/packages/d2/17/f392dfbaefdd6371335995c4f84cf3b5166cf907fdfa0aa4edc380fdfc5b/deepctr_torch-0.2.7-py3-none-any.whl (70 kB)
Requirement already satisfied: torch>=1.1.0 in /Users/henry/miniforge3/envs/py38/lib/python3.8/site-packages (from deepctr-torch==0.2.7) (1.11.0)
ERROR: Could not find a version that satisfies the requirement tensorflow (from deepctr-torch) (from versions: none)
ERROR: No matching distribution found for tensorflow
`
 想请问一下该如何解决。

**Comment by bbruceyuan** [comment]
如果直接按照 deepmatch-torch 确实没法运行。所以你可以先安装一下  `tonsorflow` 和 `pytorch-lightning` 就OK了。这么尝试可以运行，如果你不是 m1 版本的 mac 应该是不需要安装 macos 版本的 tf 吧

**Comment by HenryBao91** [comment]
不好意思，刚回复你。确实是的，我的电脑是mac m1的，非常难受。我试了，TensorFlow>2.5 的版本之后，TensorFlow 改动比较大，很多不太一样。所以我又再 windows 上开始玩儿了。 你的邮箱是多少呢？好多问题想请教一下，哈哈。

**Comment by bbruceyuan** [comment]
> 不好意思，刚回复你。确实是的，我的电脑是mac m1的，非常难受。我试了，TensorFlow>2.5 的版本之后，TensorFlow 改动比较大，很多不太一样。所以我又再 windows 上开始玩儿了。 你的邮箱是多少呢？好多问题想请教一下，哈哈。

bruceyuan123@gmail.com
