### ISSUE TITLE
想问一下，这个function不return任何东西，是个bug吗？

### ISSUE THREAD

**Issue by ajing** [bbruceyuan/DeepMatch-Torch#8]
https://github.com/bbruceyuan/DeepMatch-Torch/blob/322589cbe7f6d4efb1c4094bd6fb62f599f62c29/deepmatch_torch/utils/utils.py#L5

**Comment by ajing** [comment]
多谢，想问一下如果要加sample weight应该怎么弄？

**Comment by ajing** [comment]
这个为什么不是SparseFeat，而是VarLenSparseFeat(SparseFeat), DeepMatch 版本是用的 SparseFeat

https://github.com/bbruceyuan/DeepMatch-Torch/blob/322589cbe7f6d4efb1c4094bd6fb62f599f62c29/examples/run_youtubednn.py#L60

**Comment by bbruceyuan** [comment]
> 这个为什么不是SparseFeat，而是VarLenSparseFeat(SparseFeat), DeepMatch 版本是用的 SparseFeat
> 
> https://github.com/bbruceyuan/DeepMatch-Torch/blob/322589cbe7f6d4efb1c4094bd6fb62f599f62c29/examples/run_youtubednn.py#L60

这是因为：我在 DeepMatch-Torch 中需要依靠 输入多个 item 来模拟 sampledsoftmax。所以 item 侧需要输入多个 item_id。具体设计可见：https://github.com/bbruceyuan/DeepMatch-Torch/issues/3

如果有更好的方式也可以帮忙 pr 一下~

**Comment by bbruceyuan** [comment]
> 多谢，想问一下如果要加sample level weight应该怎么弄？

我理解这个应该指的是 loss 上的 sample level weight吧？

这种如果是 raw pytorch 就很好实现，直接在计算 loss 的时候加上 Weight， 如果是 deepmatch-torch中，你就应该在 model 中重写 _step 方法，可见：https://github.com/bbruceyuan/DeepMatch-Torch/blob/322589cbe7f6d4efb1c4094bd6fb62f599f62c29/deepmatch_torch/models/PLBaseModel.py#L167 

因为你需要传入一个参数，然后重写这个 loss 计算就OK了
